version: '2.1'
services:
  sakka-mysql:
    container_name: sakka-mysql
    image: 'mysql/mysql-server:5.7'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: thegeekyasian
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3301:3306'
    restart: always
  sakka-app:
    image: sakka-spring-boot-app
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    ports:
      - '8087:8080'
    volumes:
      - /data/sakka-spring-boot-app
    depends_on:
      sakka-mysql:
        condition: service_healthy

